theme: jekyll-theme-minimal
title: Let's Build a Simiple Database
description: Writing a sqlite clone from scratch in C
collections:
  parts:
    output: true
defaults:
  - scope:
      path: ""
      type: parts
    values:
      layout: default
